### ISSUE TITLE
peertube to support threefold connect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-peertube#1]
## phase 1

- [x] prepare a fork
- [x] prepare the build pipeline (build pipelines don't work on forks on github)
- [x] prepare the helm charts
- [x] make sure VDC marketplace works against the forked solutions
- [x] integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?
- [x] use the current [oauth proxy](https://oauth.threefold.io) 

note: this issue doesn't address anything related to mobile/desktop apps for the solutions, it'd be only usable from the web browser

**Comment by hossnys** [comment]
can't login with my 3bot account to a deployed peertube solution on testnet vdc : https://samir1-peertube-test.webg2test.grid.tf/

![Screenshot from 2021-02-23 19-46-47](https://user-images.githubusercontent.com/26298009/108885287-4c80dd00-7610-11eb-92ab-9218b491f9ac.png)

**Comment by hossnys** [comment]
closing this one because of  https://github.com/threefoldtech/tf-peertube/issues/2 will take care of this error.

**Comment by RafyAmgadBenjamin** [comment]
I got the same behavior while trying to login to `peertube` without registering before using my threefold email
Issue 
https://github.com/threefoldtech/js-sdk/issues/2654

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-03-21 19-20-21](https://user-images.githubusercontent.com/26298009/111915207-c1173200-8a7d-11eb-89bf-3d6e39b5f809.png)
